### ISSUE TITLE
Error with PasswordSafe in WebStorm 2016.3

### ISSUE THREAD

**Issue by TomasJancik** [Topher84/NetSuite-Tools-For-WebStorm#9]
I updated to WebStorm 2016.3 and I get an error whenever I do some action that requests for WebStorm master password

com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.getMasterKeyProvider()Lcom/intellij/ide/passwordSafe/impl/providers/masterKey/MasterKeyPasswordSafe;
java.lang.NoSuchMethodError: com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.getMasterKeyProvider()Lcom/intellij/ide/passwordSafe/impl/providers/masterKey/MasterKeyPasswordSafe;
	at projectsettings.ProjectSettingsController.getProjectPassword(ProjectSettingsController.java:106)
	at projectsettings.ProjectSettingsController.getNSAccountForProject(ProjectSettingsController.java:122)
	at actions.UploadAction.actionPerformed(UploadAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Topher84** [comment]
Looks like JetBrains removed something with the latest 2016.3 release. I will have to investigate and see what replaced the method.

**Comment by Topher84** [comment]
I have a fix I am testing now.

**Comment by Topher84** [comment]
This should be resolved in v1.0.10. This version is only available for 2016.3 versions (builds since 163.0). Every other version should see the working 1.0.9.

**Comment by TomasJancik** [comment]
I had to set the Project settings again. but now it works again. thanks
